app_name = "my server"


[log]
log_file_path = ".\\log\\"
log_file_name = "server.log"

# 日志等级
log_level = "DEBUG"

[mysql]
ip = "127.0.0.1"
port = "3306"
user = "webserver"
password = "1992zhou1319"
database = "webserver"

[redis]
ip = "127.0.0.1"
port = 6390
password = ""
db = 0
poolsize = 100